-- Timefork schema (Week 1).
-- Applied automatically on first container boot (see docker-compose.yml).

-- One row per agent run.
CREATE TABLE IF NOT EXISTS runs (
    -- Generated by the application, so the caller knows it before the first insert.
    run_id      TEXT         PRIMARY KEY,
    agent_name  TEXT         NOT NULL,
    input       JSONB        NOT NULL,
    status      TEXT         NOT NULL DEFAULT 'running'
                             CHECK (status IN ('running', 'completed', 'failed')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Append-only event log: one ordered stream of entries per run.
CREATE TABLE IF NOT EXISTS events (
    run_id      TEXT         NOT NULL REFERENCES runs(run_id),
    -- Dense (1, 2, 3, ...) and supplied by the writer, not auto-generated:
    -- replay needs exact, gap-free positions it can address directly.
    seq         BIGINT       NOT NULL,
    type        TEXT         NOT NULL,
    payload     JSONB        NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- One event per slot: a duplicate append fails loudly instead of
    -- corrupting history. Also the index that serves ordered reads.
    PRIMARY KEY (run_id, seq)
);
